import type { Difference } from 'microdiff'
import { NameEntry, Names } from './types'

export function debugLog(message: string, ...data: unknown[]) {
  console.debug(`Deadname Remover: ${message}`, ...data)
}

export function errorLog(message: string, ...data: unknown[]) {
  console.error(`Deadname Remover: ${message}`, ...data)
}

/**
 * Checks if there are any duplicate deadnames across all name categories (first, middle, last)
 * @param nameMappings - Object containing arrays of NameEntry for each name category
 * @returns boolean - true if no duplicates found, false if duplicates exist
 */
export function checkForDuplicateDeadnames(nameMappings: Names) {
  const nameTuples = (Object.values(nameMappings).flat() as NameEntry[]).flatMap(({ mappings }) => mappings[0])
  const duplicates = nameTuples.filter((item, index) => nameTuples.indexOf(item) !== index)
  return duplicates.length === 0
}

/**
 * Filters out empty arrays from the diff generated by microdiff
 * @param diff - The diff to filter
 * @returns The filtered diff
 */
export function filterEmptyArraysFromDiff(diff: Difference[]) {
  return diff.filter(change =>
    change.type !== 'CREATE'
    || !(Array.isArray(change.value) && change.value[0] === '' && change.value[1] === ''),
  )
}

/**
 * Compares two Names arrays deeply to check for any changes
 * @param previous - Previous Names array
 * @param current - Current Names array
 * @returns boolean - true if arrays are different, false if they're the same
 */
export function haveNamesChanged(previous: Names | undefined, current: Names): boolean {
  if (!previous) return true

  // Compare each category (first, middle, last names)
  for (const category in previous) {
    const prevNames = previous[category as keyof Names]
    const currNames = current[category as keyof Names]

    // Check if arrays exist and have same length
    if (prevNames.length !== currNames.length) {
      return true
    }

    // Compare each [deadname, chosenname] tuple
    for (let i = 0; i < prevNames.length; i++) {
      const [prevDead, prevChosen] = prevNames[i].mappings
      const [currDead, currChosen] = currNames[i].mappings

      if (prevDead !== currDead || prevChosen !== currChosen) {
        return true
      }
    }
  }

  return false
}

export function kebabToCamel(str: string): string {
  return str.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())
}
